version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3307
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      timeout: 10s
#      retries: 10
    volumes:
      - dbauthTesting:/var/lib/mysql
    networks:
      - authNetTesting
  authenticationDBMigraton:
    image: authenticationdbmigration
    environment:
      - AUTHENTICATION_DATABASE_URL=authenticationDB:3307
#    depends_on:
#      authenticationDB:
#        condition: service_healthy
    networks:
      - authNetTesting
  authentication:
    image: authentication
    environment:
      - AUTHENTICATION_DATABASE_URL=authenticationDB:3307
#    depends_on:
#      - authenticationDBMigraton
    ports:
      - 5002:5002
    networks:
      - authNetTesting
  electionProcessDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3309
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
#      timeout: 10s
#      retries: 10
    volumes:
      - dbelectTesting:/var/lib/mysql
    networks:
      - adminNetTesting
  electionProcessDBMigraton:
    image: electionprocessdbmigration
    environment:
      - ELECTION_PROCESS_DATABASE_URL=electionProcessDB:3309
      - REDIS_HOST=redis
#    depends_on:
#      electionProcessDB:
#        condition: service_healthy
    networks:
      - adminNetTesting
  admin:
    image: admin
    environment:
      - ELECTION_PROCESS_DATABASE_URL=electionProcessDB:3309
      - REDIS_HOST=redis
#    depends_on:
#      - electionProcessDBMigraton
#      - authentication
    ports:
      - 5000:5000
    networks:
      - adminNetTesting
  official:
    image: official
    environment:
      - ELECTION_PROCESS_DATABASE_URL=electionProcessDB:3309
      - REDIS_HOST=redis
#    depends_on:
#      - deamon
    ports:
      - 5001:5001
    networks:
      - officialNetTesting
      - adminNetTesting
  deamon:
    image: deamon
    environment:
      - ELECTION_PROCESS_DATABASE_URL=electionProcessDB:3309
      - REDIS_HOST=redis
#    depends_on:
#      - admin
    networks:
      - officialNetTesting
      - adminNetTesting
  redis:
    image: redis
    networks:
      - officialNetTesting
  adminer:
    image: adminer
    networks:
      - authNetTesting
      - officialNetTesting
      - adminNetTesting

volumes:
  dbauthTesting:
  dbelectTesting:

networks:
  authNetTesting:
  officialNetTesting:
  adminNetTesting: