version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3307
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - dbauth:/var/lib/mysql
    networks:
      - authNet
  authenticationDBMigraton:
    image: authenticationdbmigration
    environment:
      - AUTHENTICATION_DATABASE_URL=authenticationDB:3307
#    depends_on:
#      authenticationDB:
#        condition: service_healthy
    networks:
      - authNet
  authentication:
    image: authentication
    environment:
      - AUTHENTICATION_DATABASE_URL=authenticationDB:3307
#    depends_on:
#      - authenticationDBMigraton
    ports:
      - 5002:5002
    networks:
      - authNet
  electionProcessDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3309
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbelect:/var/lib/mysql
    networks:
      - adminNet
  electionProcessDBMigraton:
    image: electionprocessdbmigration
    environment:
      - ELECTION_PROCESS_DATABASE_URL=electionProcessDB:3309
      - REDIS_HOST=redis
#    depends_on:
#      electionProcessDB:
#        condition: service_healthy
    networks:
      - adminNet
  admin:
    image: admin
    environment:
      - ELECTION_PROCESS_DATABASE_URL=electionProcessDB:3309
      - REDIS_HOST=redis
#    depends_on:
#      - electionProcessDBMigraton
#      - authentication
    ports:
      - 5003:5003
    networks:
      - adminNet
  official:
    image: official
    environment:
      - ELECTION_PROCESS_DATABASE_URL=electionProcessDB:3309
      - REDIS_HOST=redis
#    depends_on:
#      - deamon
    ports:
      - 5001:5001
    networks:
      - officialNet
      - adminNet
    deploy:
      replicas: 3
  deamon:
    image: deamon
    environment:
      - ELECTION_PROCESS_DATABASE_URL=electionProcessDB:3309
      - REDIS_HOST=redis
#    depends_on:
#      - admin
    networks:
      - officialNet
      - adminNet
  redis:
    image: redis
    networks:
      - officialNet

volumes:
  dbauth:
  dbelect:

networks:
  authNet:
    driver: overlay
  officialNet:
    driver: overlay
  adminNet:
    driver: overlay