"""First migration

Revision ID: a29db492bd0f
Revises: 
Create Date: 2021-08-30 23:57:00.406094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a29db492bd0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('pollNumber', sa.Integer(), nullable=True))
    op.drop_constraint('votes_ibfk_2', 'votes', type_='foreignkey')
    op.drop_column('votes', 'participantId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('participantId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('votes_ibfk_2', 'votes', 'participants', ['participantId'], ['id'])
    op.drop_column('votes', 'pollNumber')
    # ### end Alembic commands ###
